name: Update OFAC Sanctions List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  update:
    name: Update OFAC Sanctions List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Install dependencies
        run: pnpm i
      - name: Update dependencies
        run: pnpm up
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Compile
        run: pnpm run build
      - name: Run script
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        run: pnpm run start
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "blocked-addresses.ts"
          message: "Update Stored Addresses"
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
